---
- name: download the CMake source code
  unarchive:
    src: https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz
    dest: /usr/local/src
    remote_src: yes
    validate_certs: no
  register: cmake_src_download_result

- name: run the bootstrap script
  shell: ./bootstrap
  args:
    chdir: /usr/local/src/cmake-3.8.0
  when: cmake_src_download_result.changed

- name: build CMake
  make:
    chdir: /usr/local/src/cmake-3.8.0
  when: cmake_src_download_result.changed

- name: install CMake
  make:
    target: install
    chdir: /usr/local/src/cmake-3.8.0
  when: cmake_src_download_result.changed

- name: create the symbolic link to the CMake binary file
  file:
    src: /usr/local/bin/cmake
    dest: /usr/bin/cmake
    state: link
